/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.AdminController;
import Controllers.PaketController;
import Models.Paket;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import Models.Kurir;
import javax.swing.JList;

/**
 *
 * @author goody
 */
public class AdminView extends javax.swing.JFrame {
    private AdminController cont;
    private PaketController ctrl;
    final String nama;
    /**
     * Creates new form AdminView
     */
    public AdminView(String name) {
        initComponents();
        this.nama = name;
        this.ctrl = new PaketController();
        this.cont = new AdminController();
        
        nama_admin.setText(name);
        
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for(Paket paket : ctrl.PAKET){
            listModel.addElement(paket.getNamaPaket());
        }
        listpaket.setModel(listModel);
        show_paket.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nama_admin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listpaket = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        isi_harga = new javax.swing.JTextField();
        isi_resi = new javax.swing.JTextField();
        show_paket = new javax.swing.JLabel();
        show_berat = new javax.swing.JLabel();
        show_status = new javax.swing.JLabel();
        show_kuantitas = new javax.swing.JLabel();
        show_alamat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        show_berat1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(433, 459));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Resi   : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(180, 330, 50, 18);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Hi, ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(30, 40, 38, 32);

        nama_admin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nama_admin.setText("Admin");
        jPanel2.add(nama_admin);
        nama_admin.setBounds(70, 40, 180, 32);

        listpaket.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        listpaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listpaketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listpaket);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 140, 260);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Nama Paket  : ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 120, 85, 18);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Berat            : ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 150, 85, 18);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Kuantitas      : ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(180, 180, 84, 18);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("Alamat         : ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(180, 210, 83, 18);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("Status Pengiriman  : ");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(180, 240, 119, 18);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("Masukkan Harga & Resi:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(180, 270, 150, 18);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setText("Harga:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(180, 300, 40, 18);

        isi_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isi_hargaActionPerformed(evt);
            }
        });
        jPanel2.add(isi_harga);
        isi_harga.setBounds(230, 300, 170, 22);
        jPanel2.add(isi_resi);
        isi_resi.setBounds(230, 330, 170, 22);

        show_paket.setText("A");
        jPanel2.add(show_paket);
        show_paket.setBounds(270, 120, 120, 16);

        show_berat.setText("Kg");
        jPanel2.add(show_berat);
        show_berat.setBounds(380, 150, 20, 16);

        show_status.setText("E");
        jPanel2.add(show_status);
        show_status.setBounds(300, 240, 100, 16);

        show_kuantitas.setText("C");
        jPanel2.add(show_kuantitas);
        show_kuantitas.setBounds(270, 180, 130, 16);

        show_alamat.setText("D");
        jPanel2.add(show_alamat);
        show_alamat.setBounds(270, 210, 130, 16);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(260, 400, 90, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(70, 400, 90, 40);

        show_berat1.setText("B");
        jPanel2.add(show_berat1);
        show_berat1.setBounds(270, 150, 20, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Admin View.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 433, 459);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isi_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isi_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isi_hargaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String selected = listpaket.getSelectedValue();
        PaketController pkg = new PaketController();
        if(pkg.findPaket(selected)){
            Paket p = pkg.searchPaket(selected);
            int isiharga = Integer.parseInt(isi_harga.getText());
            String isiresi = isi_resi.getText();
            System.out.println(p.getNamaPaket());
            cont.updateStatus(p.getNamaPaket(), isiharga, isiresi);
        };

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        landingView landView = new landingView();
        landView.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void listpaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listpaketMouseClicked
        // TODO add your handling code here:
        String selected = listpaket.getSelectedValue();
        PaketController pkg = new PaketController();
        if(pkg.findPaket(selected)){
            Paket p = pkg.searchPaket(selected);
            show_paket.setText(p.getNamaPaket());
            show_berat.setText(String.valueOf(p.getBeratPaket()));
            show_kuantitas.setText(String.valueOf(p.getKuantitas()));
            show_alamat.setText(p.getAlamatTujuan());
            show_status.setText(p.isStatusPengiriman());
        }
    }//GEN-LAST:event_listpaketMouseClicked

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField isi_harga;
    private javax.swing.JTextField isi_resi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listpaket;
    private javax.swing.JLabel nama_admin;
    private javax.swing.JLabel show_alamat;
    private javax.swing.JLabel show_berat;
    private javax.swing.JLabel show_berat1;
    private javax.swing.JLabel show_kuantitas;
    private javax.swing.JLabel show_paket;
    private javax.swing.JLabel show_status;
    // End of variables declaration//GEN-END:variables
}
