/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author goody
 */
public class landingView extends javax.swing.JFrame {

    /**
     * Creates new form landingView
     */
    public landingView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnDaftarAdmin = new javax.swing.JButton();
        btnDaftarUser = new javax.swing.JButton();
        btnDaftarKurir = new javax.swing.JButton();
        btnLoginAdmin = new javax.swing.JButton();
        btnLoginUser = new javax.swing.JButton();
        btnLoginKurir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(410, 545));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("- Mendaftar Sebagai Kurir:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 230, 220, 19);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("WELCOME TO CEPETDONG");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 40, 324, 32);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Udah Punya Akun?");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 270, 170, 24);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("- Login Sebagai Kurir:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 360, 200, 19);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("- Mendaftar Sebagai Pengirim:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 200, 220, 19);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gak Punya Akun?");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 140, 155, 24);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("- Mendaftar Sebagai Admin:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 170, 200, 19);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("- Login Sebagai Admin:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 300, 200, 19);

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("- Login Sebagai Pengirim:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 330, 200, 19);

        btnDaftarAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnDaftarAdmin.setText("Daftar");
        btnDaftarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarAdmin);
        btnDaftarAdmin.setBounds(290, 170, 70, 20);

        btnDaftarUser.setBackground(new java.awt.Color(255, 255, 255));
        btnDaftarUser.setText("Daftar");
        btnDaftarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarUser);
        btnDaftarUser.setBounds(290, 200, 70, 20);

        btnDaftarKurir.setBackground(new java.awt.Color(255, 255, 255));
        btnDaftarKurir.setText("Daftar");
        btnDaftarKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarKurirActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarKurir);
        btnDaftarKurir.setBounds(290, 230, 70, 20);

        btnLoginAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginAdmin.setText("Masuk");
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginAdmin);
        btnLoginAdmin.setBounds(290, 300, 80, 20);

        btnLoginUser.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginUser.setText("Masuk");
        btnLoginUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginUser);
        btnLoginUser.setBounds(290, 330, 80, 20);

        btnLoginKurir.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginKurir.setText("Masuk");
        btnLoginKurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginKurirActionPerformed(evt);
            }
        });
        jPanel1.add(btnLoginKurir);
        btnLoginKurir.setBounds(290, 360, 80, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/BG.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 545);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDaftarKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarKurirActionPerformed
        // TODO add your handling code here:
        RegisterViewKurir regView = new RegisterViewKurir();
        regView.show();
        dispose();
    }//GEN-LAST:event_btnDaftarKurirActionPerformed

    private void btnDaftarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarAdminActionPerformed
        // TODO add your handling code here:
        LoginViewAdmin logView = new LoginViewAdmin();
        logView.show();
        dispose();
    }//GEN-LAST:event_btnDaftarAdminActionPerformed

    private void btnDaftarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarUserActionPerformed
        // TODO add your handling code here:
        RegisterViewPengirim regViewPengirim = new RegisterViewPengirim();
        regViewPengirim.show();
        dispose();
    }//GEN-LAST:event_btnDaftarUserActionPerformed

    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        // TODO add your handling code here:
        LoginViewAdmin logView = new LoginViewAdmin();
        logView.show();
        dispose();
    }//GEN-LAST:event_btnLoginAdminActionPerformed

    private void btnLoginUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginUserActionPerformed
        // TODO add your handling code here:
        LoginViewPengirim logViewPengirim = new LoginViewPengirim();
        logViewPengirim.show();
        dispose();
    }//GEN-LAST:event_btnLoginUserActionPerformed

    private void btnLoginKurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginKurirActionPerformed
        // TODO add your handling code here:
        LoginViewKurir logViewKurir = new LoginViewKurir();
        logViewKurir.show();
        dispose();
    }//GEN-LAST:event_btnLoginKurirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landingView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarAdmin;
    private javax.swing.JButton btnDaftarKurir;
    private javax.swing.JButton btnDaftarUser;
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JButton btnLoginKurir;
    private javax.swing.JButton btnLoginUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
