/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.PaketController;
import javax.swing.JOptionPane;

/**
 *
 * @author goody
 */
public class PengirimView extends javax.swing.JFrame {

    private PaketController ctrl;
    final String id;
    /**
     * Creates new form PengirimView
     */
    public PengirimView(String ID) {
        initComponents();
        this.id = ID;
        this.ctrl = new PaketController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        input_alamat = new javax.swing.JTextField();
        input_paket = new javax.swing.JTextField();
        input_berat = new javax.swing.JTextField();
        input_kuantitas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(424, 459));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Alamat          : ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 250, 100, 19);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setText("Kirim Barang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 400, 110, 40);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(40, 400, 100, 40);
        jPanel1.add(input_alamat);
        input_alamat.setBounds(140, 250, 220, 110);

        input_paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_paketActionPerformed(evt);
            }
        });
        jPanel1.add(input_paket);
        input_paket.setBounds(140, 130, 220, 22);
        jPanel1.add(input_berat);
        input_berat.setBounds(140, 170, 190, 22);
        jPanel1.add(input_kuantitas);
        input_kuantitas.setBounds(140, 210, 220, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("MASUKKAN DATA PAKET ANDA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 371, 32);

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("KG");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 170, 20, 19);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Nama Paket  : ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 130, 92, 19);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Berat            :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 170, 86, 19);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Kuantitas      :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 210, 100, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/PengirimView.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 424, 459);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String namaPaket = input_paket.getText();
            String idPaket = this.id;
            int beratPaket = Integer.parseInt(input_berat.getText());
            int kuantitas = Integer.parseInt(input_kuantitas.getText());
            int hargaPaket = 0;
            String resiPaket = "";
            String alamatTujuan = input_alamat.getText();
            String statusPengiriman = "";

            if (namaPaket.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Data tidak boleh kosong");
                this.requestFocus();
            }
            else {
                ctrl.addPaket(namaPaket, idPaket, beratPaket, kuantitas, hargaPaket, resiPaket, alamatTujuan, statusPengiriman);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Paket telah terinput");
                PengirimView logView = new PengirimView(this.id);
                logView.show();
            }
        } catch (Exception e) {
            System.out.println("Register Gagal");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        landingView landView = new landingView();
        landView.show();
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input_paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_paketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_paketActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_alamat;
    private javax.swing.JTextField input_berat;
    private javax.swing.JTextField input_kuantitas;
    private javax.swing.JTextField input_paket;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
