/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.KurirController;
import javax.swing.JOptionPane;

/**
 *
 * @author goody
 */
public class RegisterViewKurir extends javax.swing.JFrame {

    /**
     * Creates new form RegisterViewKurir
     */
    public RegisterViewKurir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_nohp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        input_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        config_idkurir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        input_user_reg3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_reg = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_to_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(434, 510));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("REGISTER COURIER PAGE");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 10, 289, 32);

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("No HP");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 260, 50, 19);

        input_nohp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nohpActionPerformed(evt);
            }
        });
        jPanel1.add(input_nohp);
        input_nohp.setBounds(120, 260, 270, 22);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 210, 50, 19);

        input_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_idActionPerformed(evt);
            }
        });
        jPanel1.add(input_id);
        input_id.setBounds(120, 210, 270, 22);

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("ID Kurir");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 310, 60, 19);

        config_idkurir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                config_idkurirActionPerformed(evt);
            }
        });
        jPanel1.add(config_idkurir);
        config_idkurir.setBounds(120, 310, 270, 22);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("data-data dibawah ini");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 110, 350, 19);

        input_user_reg3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_user_reg3ActionPerformed(evt);
            }
        });
        jPanel1.add(input_user_reg3);
        input_user_reg3.setBounds(120, 160, 270, 22);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Name");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 160, 50, 19);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Untuk mendaftar sebagai kurir silahkan masukkan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 90, 350, 19);

        btn_reg.setBackground(new java.awt.Color(255, 255, 255));
        btn_reg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_reg.setText("Register");
        btn_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regActionPerformed(evt);
            }
        });
        jPanel1.add(btn_reg);
        btn_reg.setBounds(289, 365, 90, 40);

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Sudah Mempunyai Akun?");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(170, 450, 170, 40);

        btn_to_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_to_login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_to_login.setText("Login");
        btn_to_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_to_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_to_login);
        btn_to_login.setBounds(333, 455, 90, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/RegisterViewKurir.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 434, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nohpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nohpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nohpActionPerformed

    private void input_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_idActionPerformed

    private void config_idkurirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_config_idkurirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_config_idkurirActionPerformed

    private void input_user_reg3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_user_reg3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_user_reg3ActionPerformed

    private void btn_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regActionPerformed
        // TODO add your handling code here:
        try {
            String nama = input_nohp.getText();
            String ID = input_id.getText();
            int nohp = Integer.parseInt(input_nohp.getText());
            //            String password = String.valueOf(input_pass_reg.getPassword());
            //            String confirmPassword = String.valueOf(input_conf_reg.getPassword());
            String IDKurir = String.valueOf(config_idkurir.getText());

            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Username tidak boleh kosong");
                this.requestFocus();
            }
            else {
                ctrl.registerUser(IDKurir, ID,nama, nohp);
                this.dispose();
                LoginViewAdmin logView = new LoginViewAdmin();
                logView.show();
            }
        } catch (Exception e) {
            System.out.println("Register Gagal");
        }
    }//GEN-LAST:event_btn_regActionPerformed

    private void btn_to_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_to_loginActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginViewKurir logView = new LoginViewKurir();
        logView.show();
    }//GEN-LAST:event_btn_to_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterViewKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterViewKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterViewKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterViewKurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterViewKurir().setVisible(true);
            }
        });
    }

    private KurirController ctrl = new KurirController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reg;
    private javax.swing.JButton btn_to_login;
    private javax.swing.JTextField config_idkurir;
    private javax.swing.JTextField input_id;
    private javax.swing.JTextField input_nohp;
    private javax.swing.JTextField input_user_reg3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
